In [2]:
import boto3
import pickle
import pandas as pd
from io import BytesIO
import sys

In [8]:
bucket_name = 'delaynomore-data-pond'
file_key = 'data/random_subset_100K.pkl'

# Create an S3 client
s3 = boto3.client('s3')

# Download the file as an in-memory object
response = s3.get_object(Bucket=bucket_name, Key=file_key)
print("File Size (in bytes):", response['ContentLength'])
stream = response['Body']

File Size (in bytes): 22768393

In [9]:
data = pickle.load(stream)
sys.getsizeof(data)

52809782

In [10]:
data.head()

,expected_arrival_time,expected_departure_time,date,service_id,stop_id,stop_code,stop_sequence,stop_name,stop_lat,stop_lon,...,pickup_type,drop_off_type,wheelchair_boarding,wheelchair_accessible,bikes_allowed,route_id,route_short_name,route_long_name,route_type,route_color
32704686,2024-07-21 07:55:00,2024-07-21 07:55:00,2024-07-21,3,6122,6640,14,Parliament St at King St East,43.652780,-79.363342,...,0,0,1,1,1,72162,65,PARLIAMENT,3,FF0000
32119625,2024-07-14 15:22:00,2024-07-14 15:22:00,2024-07-14,3,9630,702,9,Caledonia Rd at Bentworth Ave,43.719708,-79.468754,...,0,0,1,1,1,72133,47,LANSDOWNE,3,FF0000
20449236,2024-07-15 21:35:00,2024-07-15 21:35:00,2024-07-15,1,6745,6072,26,Sheppard Ave West at Keele St,43.744972,-79.486103,...,0,0,1,1,1,72184,84,SHEPPARD WEST,3,FF0000
15649322,2024-06-28 21:05:00,2024-06-28 21:05:00,2024-06-28,1,9247,5273,54,Lawrence Ave East at Greencedar Circt East Side,43.758141,-79.232683,...,0,0,1,1,1,72151,54,LAWRENCE EAST,3,FF0000
7483210,2024-07-09 10:52:00,2024-07-09 10:52:00,2024-07-09,1,3631,11710,5,Bedford Rd at Dupont St,43.676063,-79.400322,...,0,0,1,1,1,72076,26,DUPONT,3,FF0000

In [11]:
data.dtypes

expected_arrival_time      datetime64[ns]
expected_departure_time    datetime64[ns]
date                       datetime64[ns]
service_id                          int64
stop_id                             int64
stop_code                           int64
stop_sequence                       int64
stop_name                          object
stop_lat                          float64
stop_lon                          float64
direction_id                        int64
shape_id                            int64
shape_dist_traveled               float64
dist_traveled_from                float64
dist_to_travel                    float64
trip_id                             int64
trip_headsign                      object
block_id                            int64
pickup_type                         int64
drop_off_type                       int64
wheelchair_boarding                 int64
wheelchair_accessible               int64
bikes_allowed                       int64
route_id                            int64
route_short_name                    int64
route_long_name                    object
route_type                          int64
route_color                        object
dtype: object