In [1]:
import numpy as np
import pandas as pd 

# read in stop_times txt file
# stop_id is the unique id that defined the stop, this is different from the public stop number 
# value on the TTC website, a mapping is found in stops.txt, stop_sequence represents which stop 
# from the very first stop it is 
stop_times_df = pd.read_csv("data/stop_times.txt", sep=",", header=0)
stop_times_df.head(10)

FileNotFoundError: [Errno 2] No such file or directory: 'data/stop_times.txt'

In [2]:
# read in stops txt file 
# maps the internal(?) stop_id to the external stop_code as shown in https://www.ttc.ca/routes-and-schedules
stops_df = pd.read_csv("data/stops.txt", sep=",", header=0)
stops_df.head(10)

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding
0,262,662,Danforth Rd at Kennedy Rd,NaN,43.714379,-79.260939,NaN,NaN,NaN,NaN,NaN,1
1,263,929,Davenport Rd at Bedford Rd,NaN,43.674448,-79.399659,NaN,NaN,NaN,NaN,NaN,1
2,264,940,Davenport Rd at Dupont St,NaN,43.675511,-79.401938,NaN,NaN,NaN,NaN,NaN,2
3,265,1871,Davisville Ave at Cleveland St,NaN,43.702088,-79.378112,NaN,NaN,NaN,NaN,NaN,1
4,266,11700,Disco Rd at Attwell Dr,NaN,43.701362,-79.594843,NaN,NaN,NaN,NaN,NaN,1
5,267,3478,Disco Rd at Attwell Dr,NaN,43.701043,-79.595806,NaN,NaN,NaN,NaN,NaN,1
6,268,3479,Disco Rd at Carlingview Dr East Side,NaN,43.699810,-79.600769,NaN,NaN,NaN,NaN,NaN,1
7,269,3480,Disco Rd at Carlingview Dr,NaN,43.699929,-79.601176,NaN,NaN,NaN,NaN,NaN,1
8,270,14258,Don Mills Rd at Eglinton Ave East,NaN,43.720674,-79.339121,NaN,NaN,NaN,NaN,NaN,1
9,271,9125,Don Mills Rd at Eglinton Ave East North Side,NaN,43.721373,-79.338926,NaN,NaN,NaN,NaN,NaN,1

In [3]:
# read in trips.txt
# each trip_id maps tp a route_id
trips_df = pd.read_csv("data/trips.txt", sep=",", header=0)
trips_df.head(10)

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,72700,1,47773772,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031217,1,1
1,72700,1,47773773,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
2,72700,1,47773779,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
3,72700,1,47773778,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
4,72700,1,47773777,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
5,72700,1,47773776,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
6,72700,1,47773775,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
7,72700,1,47773784,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
8,72700,1,47773774,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079188,1031216,1,1
9,72700,1,47773769,EAST - 10 VAN HORNE towards VICTORIA PARK,NaN,0,2079187,1031216,1,1

In [4]:
# read in routes.txt
# maps the route_id to the bus number
routes_df = pd.read_csv("data/routes.txt", sep=",", header=0)
routes_df.head(10)

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
0,72927,1,1,LINE 1 (YONGE-UNIVERSITY),NaN,1,NaN,D5C82B,000000
1,72700,1,10,VAN HORNE,NaN,3,NaN,FF0000,FFFFFF
2,72701,1,100,FLEMINGDON PARK,NaN,3,NaN,FF0000,FFFFFF
3,72702,1,101,DOWNSVIEW PARK,NaN,3,NaN,FF0000,FFFFFF
4,72703,1,102,MARKHAM RD.,NaN,3,NaN,FF0000,FFFFFF
5,72704,1,104,FAYWOOD,NaN,3,NaN,FF0000,FFFFFF
6,72705,1,105,DUFFERIN NORTH,NaN,3,NaN,FF0000,FFFFFF
7,72706,1,106,SENTINEL,NaN,3,NaN,FF0000,FFFFFF
8,72707,1,107,YORK UNIVERSITY HEIGHTS,NaN,3,NaN,FF0000,FFFFFF
9,72708,1,108,DRIFTWOOD,NaN,3,NaN,FF0000,FFFFFF

In [5]:
# read in calendar.txt which stores which days of the week each service_id is and the 
# schedule range in terms of start date and end date 
calendar_df = pd.read_csv("data/calendar.txt", sep=",", header=0)
calendar_df.head(10)

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,1,1,1,1,1,1,0,0,20241006,20241116
1,2,0,0,0,0,0,1,0,20241006,20241116
2,3,0,0,0,0,0,0,1,20241006,20241116
3,4,0,0,0,0,0,0,0,20241006,20241116
4,401,0,0,0,0,0,0,0,20241006,20241116
5,501,0,0,0,0,0,0,0,20241006,20241116
6,4401,0,0,0,0,0,0,0,20241006,20241116
7,4501,0,0,0,0,0,0,0,20241006,20241116
8,502,0,0,0,0,0,0,0,20241006,20241116
9,2903,0,0,0,0,0,0,0,20241006,20241116

From the above, we can see that service_id==1 means the schedule from Monday to Friday, 2 means saturday and 3 means sunday.

In [6]:
# join stop_time df with stops df on stop_id
overall_df = pd.merge(stop_times_df[["trip_id", "arrival_time", "departure_time", "stop_id", "stop_sequence"]], stops_df[["stop_id", "stop_code", "stop_name", "stop_lat", "stop_lon"]], on=["stop_id"])

# join stop_times_combined with trips_df on trip_id
overall_df = pd.merge(overall_df, trips_df[["trip_id", "route_id", "service_id", "trip_headsign", "direction_id"]], on=["trip_id"])

# join with routes_df on route_id for route_short_name (the bus number) and route_long_name (the official route name)
overall_df = pd.merge(overall_df, routes_df[["route_id", "route_short_name", "route_long_name"]], on=["route_id"])

overall_df = overall_df[["route_short_name", "route_long_name", "trip_headsign", "route_id", "trip_id", "arrival_time", "departure_time", "stop_id", "stop_code", "stop_name", "stop_sequence", "direction_id", "service_id"]]
overall_df = overall_df.rename(columns={"stop_sequence":"stop #", "trip_headsign": "route_direction"})

overall_df.head(10)

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
0,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:45:00,18:45:00,15182,15330,Don Mills Station,1,0,1
1,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:45:56,18:45:56,3807,1949,Don Mills Rd at Leith Hill Rd North Side,2,0,1
2,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:46:42,18:46:42,6904,1929,Don Mills Rd at Fairview Mall Dr North Side,3,0,1
3,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:47:55,18:47:55,1163,1938,Don Mills Rd at Godstone Rd,4,0,1
4,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:48:58,18:48:58,7723,1919,Don Mills Rd at Deerford Rd,5,0,1
5,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:50:08,18:50:08,2498,7384,Van Horne Ave at Don Mills Rd East Side,6,0,1
6,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:50:40,18:50:40,805,7387,Van Horne Ave at Hobart Dr,7,0,1
7,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:51:09,18:51:09,1047,7390,Van Horne Ave at Houston Cres (West),8,0,1
8,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:51:40,18:51:40,8848,7391,Van Horne Ave at Kingslake Rd,9,0,1
9,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:52:58,18:52:58,4206,7385,Van Horne Ave at Edmonton Rd East Side,10,0,1

In [7]:
# filter for specific columns 
# all rows of bus 10 and Don Mills Station
bus10_at_donmillsstation = overall_df[(overall_df["route_short_name"] == 10) & (overall_df["stop_code"] == 15330) & (overall_df["direction_id"] == 0)]

In [8]:
bus10_at_donmillsstation

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
0,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773766,18:45:00,18:45:00,15182,15330,Don Mills Station,1,0,1
19,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773767,18:15:00,18:15:00,15182,15330,Don Mills Station,1,0,1
38,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773768,17:45:00,17:45:00,15182,15330,Don Mills Station,1,0,1
57,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773769,14:15:00,14:15:00,15182,15330,Don Mills Station,1,0,1
76,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773770,14:45:00,14:45:00,15182,15330,Don Mills Station,1,0,1
95,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773771,15:15:00,15:15:00,15182,15330,Don Mills Station,1,0,1
114,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773773,5:30:00,5:30:00,15182,15330,Don Mills Station,1,0,1
133,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773774,9:00:00,9:00:00,15182,15330,Don Mills Station,1,0,1
152,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773775,8:00:00,8:00:00,15182,15330,Don Mills Station,1,0,1
171,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773776,7:30:00,7:30:00,15182,15330,Don Mills Station,1,0,1
190,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773777,7:00:00,7:00:00,15182,15330,Don Mills Station,1,0,1
209,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773778,6:30:00,6:30:00,15182,15330,Don Mills Station,1,0,1
228,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773779,6:00:00,6:00:00,15182,15330,Don Mills Station,1,0,1
247,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773780,17:15:00,17:15:00,15182,15330,Don Mills Station,1,0,1
266,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773781,16:45:00,16:45:00,15182,15330,Don Mills Station,1,0,1
285,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773782,16:15:00,16:15:00,15182,15330,Don Mills Station,1,0,1
304,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773783,15:45:00,15:45:00,15182,15330,Don Mills Station,1,0,1
323,10,VAN HORNE,EAST - 10 VAN HORNE towards VICTORIA PARK,72700,47773784,8:30:00,8:30:00,15182,15330,Don Mills Station,1,0,1

In [9]:
# investigate timestamps of HH > 23
night_bus = overall_df[(overall_df["trip_id"] == 47784429) & (overall_df["stop_id"] == 15135)]
night_bus

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
1437252,301,QUEEN,EAST - 301 QUEEN towards NEVILLE PARK,72771,47784429,30:00:55,30:00:55,15135,15344,Queen St East at Glen Manor Dr,84,0,1

In [10]:
# investigate early morning buses
morning_bus = overall_df[(overall_df["trip_id"] == 47784595) & (overall_df["stop_id"] == 6052)]
morning_bus

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
3669511,31,GREENWOOD,SOUTH - 31 GREENWOOD towards QUEEN & EASTERN,72778,47784595,6:32:47,6:32:47,6052,1786,Coxwell Ave at Danforth Ave,2,0,1

In [11]:
# do additional processing on 24H, 25H, 26H, 27H, 28H, 29H, and 30H which corresponds to 12 AM, 1 AM, 2AM, 3AM, 4AM, 5AM, 6AM
# for night buses (might be a way to distinguish nigh buses if no other ways?)
def standardize_time(time_str):
    if time_str[1] != ':' and int(time_str[:2]) > 23:
        new_str = "0" + str(int(time_str[:2]) - 24) + time_str[2:]
        # slice the seconds digit 
        new_str = new_str[:-3]
        return new_str
    else:
        if time_str[1] == ':':
            time_str = "0" + time_str
        return time_str[:-3]
    
arrival_time_standard = overall_df["arrival_time"].apply(standardize_time)
departure_time_standard = overall_df["departure_time"].apply(standardize_time)
overall_df["arrival_time"] = arrival_time_standard
overall_df["departure_time"] = departure_time_standard

# convert the arrival and departure time into standard datetime formats 
overall_df['arrival_time'] = pd.to_datetime(overall_df['arrival_time'], format="%H:%M").dt.time
overall_df['departure_time'] = pd.to_datetime(overall_df['departure_time'], format="%H:%M").dt.time

In [12]:
# build a function that extracts the bus schedule for a bus given the bus number, stop_code (the stop code on the TTC website), 
# and day of the week in the format of 1-7 (monday to sunday), and direction, one of [N, S, E, W]
def get_schedule(bus, stop_code, day):
    # default to monday to friday schedule 
    service_id = 1
    if day == 6:
        service_id = 2
    if day == 7:
        service_id = 3
    results = overall_df[(overall_df["route_short_name"] == bus) & (overall_df["stop_code"] == stop_code) & (overall_df["service_id"] == service_id)]
    # sort the result by time in ascending order 
    results = results.sort_values(by="arrival_time")
    return results

In [14]:
# get the 95 bus schedule at York Mills Rd at Fenn Avenue Stop (3257) for monday-friday
get_schedule(95, 3257, 1).head(20)

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
2305039,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808228,00:04:00,00:04:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306220,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47808263,00:12:00,00:12:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2304968,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808227,00:20:00,00:20:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306277,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47808264,00:28:00,00:28:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2304897,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808226,00:36:00,00:36:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306334,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47808265,00:44:00,00:44:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306775,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808225,00:52:00,00:52:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306533,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47808221,01:00:00,01:00:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306704,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808224,01:08:00,01:08:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306590,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47808222,01:16:00,01:16:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306391,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808218,01:24:00,01:24:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306647,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47808223,01:32:00,01:32:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2306462,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808219,01:36:00,01:36:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2297383,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808138,05:14:00,05:14:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2298093,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808195,05:28:00,05:28:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2298164,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808198,05:38:00,05:38:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2298235,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808200,05:48:00,05:48:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2297454,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808140,05:58:00,05:58:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2297525,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808141,06:08:00,06:08:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1
2297596,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47808142,06:18:00,06:18:00,9893,3257,York Mills Rd at Fenn Ave,7,0,1

In [15]:
# get the 51 Leslie bus schedule at York Mills Rd Stop (5492) from monday-friday
get_schedule(51, 5492, 1).head(20)

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
2388631,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793686,00:00:00,00:00:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388572,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793685,00:26:00,00:26:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388513,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793684,00:53:00,00:53:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2389103,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793728,01:20:00,01:20:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2386743,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793729,05:31:00,05:31:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2386684,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793727,05:55:00,05:55:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2386625,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793726,06:19:00,06:19:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2386566,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793725,06:43:00,06:43:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2386507,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793724,07:11:00,07:11:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2386448,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793723,07:35:00,07:35:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2386389,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793722,07:59:00,07:59:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388395,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793721,08:23:00,08:23:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388336,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793720,08:47:00,08:47:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388277,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793719,09:11:00,09:11:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388218,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793718,09:35:00,09:35:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388159,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793717,09:59:00,09:59:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388100,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793716,10:23:00,10:23:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2388041,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793715,10:52:00,10:52:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2387982,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793714,11:21:00,11:21:00,9151,5492,Leslie St at York Mills Rd,30,1,1
2387923,51,LESLIE,NORTH - 51 LESLIE towards STEELES,72837,47793713,11:50:00,11:50:00,9151,5492,Leslie St at York Mills Rd,30,1,1

In [16]:
# get the 53 Steeles bus schedule at Kennedy Rd Stop (9780) on saturdays
get_schedule(53, 9780, 2).head(20)

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
782975,53,STEELES EAST,EAST - 53A STEELES EAST towards STAINES,72842,47795820,00:00:00,00:00:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
736342,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795819,00:12:00,00:12:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
782910,53,STEELES EAST,EAST - 53A STEELES EAST towards STAINES,72842,47795818,00:24:00,00:24:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
735950,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795804,00:36:00,00:36:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
783040,53,STEELES EAST,EAST - 53A STEELES EAST towards STAINES,72842,47795822,00:48:00,00:48:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
735894,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795802,01:00:00,01:00:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
782780,53,STEELES EAST,EAST - 53A STEELES EAST towards STAINES,72842,47795813,01:12:00,01:12:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
736174,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795812,01:24:00,01:24:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
782715,53,STEELES EAST,EAST - 53A STEELES EAST towards STAINES,72842,47795811,01:36:00,01:36:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
736118,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795810,01:48:00,01:48:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
782650,53,STEELES EAST,EAST - 53A STEELES EAST towards STAINES,72842,47795809,02:00:00,02:00:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
736062,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795808,02:12:00,02:12:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
782585,53,STEELES EAST,EAST - 53A STEELES EAST towards STAINES,72842,47795806,02:22:00,02:22:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
736006,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795807,02:32:00,02:32:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
728554,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795648,05:50:00,05:50:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
728498,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795647,06:03:00,06:03:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
728442,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795646,06:16:00,06:16:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
728386,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795645,06:29:00,06:29:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
728890,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795644,06:35:00,06:35:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1
728834,53,STEELES EAST,EAST - 53B STEELES EAST towards MORNINGSIDE,72842,47795643,06:42:00,06:42:00,9349,9780,Steeles Ave East at Kennedy Rd,34,0,1

In [17]:
# get the 7 Bathurst bus schedule at Neptune Dr Stop (179) on sundays
get_schedule(7, 179, 3).head(20)

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
3217417,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799834,00:05:00,00:05:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3217358,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799833,00:15:00,00:15:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3217299,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799832,00:25:00,00:25:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3217122,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799828,00:35:00,00:35:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3217063,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799827,00:45:00,00:45:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3217240,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799831,00:55:00,00:55:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3217181,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799830,01:05:00,01:05:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3217535,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799829,01:15:00,01:15:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3210555,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799716,05:01:00,05:01:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3210438,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799713,05:16:00,05:16:00,3050,179,Bathurst St at Neptune Dr,3,0,1
3210404,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799712,05:23:00,05:23:00,3050,179,Bathurst St at Neptune Dr,3,0,1
3210496,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799714,05:30:00,05:30:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3210370,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799711,05:36:00,05:36:00,3050,179,Bathurst St at Neptune Dr,3,0,1
3212192,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799825,05:46:00,05:46:00,3050,179,Bathurst St at Neptune Dr,3,0,1
3212157,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799824,06:00:00,06:00:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3210624,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799710,06:01:00,06:01:00,3050,179,Bathurst St at Neptune Dr,3,0,1
3211685,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799781,06:20:00,06:20:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3210590,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799709,06:23:00,06:23:00,3050,179,Bathurst St at Neptune Dr,3,0,1
3211626,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799780,06:32:00,06:32:00,3050,179,Bathurst St at Neptune Dr,28,0,1
3211567,7,BATHURST,SOUTH - 7 BATHURST towards BATHURST STATION,72859,47799779,06:42:00,06:42:00,3050,179,Bathurst St at Neptune Dr,28,0,1

In [18]:
# build a function that extracts the bus schedule for a bus given the bus number, stop_code (the stop code on the TTC website), 
# and day of the week in the format of 1-7 (monday to sunday), and direction, one of [N, S, E, W]
def get_route_schedule(bus, day):
    # default to monday to friday schedule 
    service_id = 1
    if day == 6:
        service_id = 2
    if day == 7:
        service_id = 3
    results = overall_df[(overall_df["route_short_name"] == bus) & (overall_df["service_id"] == service_id)]
    # sort the result by time in ascending order 
    results = results.sort_values(by="arrival_time")
    return results

In [20]:
get_route_schedule(95, 7)

,bus,route_name,route_direction,route_id,trip_id,arrival_time,departure_time,stop_id,stop_code,stop_name,stop #,direction_id,service_id
2367083,95,YORK MILLS,WEST - 95 YORK MILLS towards YORK MILLS STATION,72906,47866837,00:00:00,00:00:00,4280,7710,Ellesmere Rd at Borough Approach West,26,1,3
2366484,95,YORK MILLS,WEST - 95 YORK MILLS towards YORK MILLS STATION,72906,47866828,00:00:00,00:00:00,1655,7701,Ellesmere Rd at Mornelle Crt,5,1,3
2326063,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47866595,00:00:00,00:00:00,4924,7702,Ellesmere Rd at Morningside Ave,55,0,3
2366564,95,YORK MILLS,WEST - 95 YORK MILLS towards YORK MILLS STATION,72906,47866829,00:00:00,00:00:00,5470,7714,Ellesmere Rd at Pharmacy Ave,33,1,3
2366563,95,YORK MILLS,WEST - 95 YORK MILLS towards YORK MILLS STATION,72906,47866829,00:00:00,00:00:00,14573,7686,Ellesmere Rd at Claudius Gate,32,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2325881,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47866592,23:59:00,23:59:00,4202,9086,York Mills Rd at Upjohn Rd,16,0,3
2325882,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47866592,23:59:00,23:59:00,5711,9070,York Mills Rd at Don Mills Rd,17,0,3
2325950,95,YORK MILLS,EAST - 95A YORK MILLS towards PORT UNION,72906,47866593,23:59:00,23:59:00,4465,7719,Ellesmere Rd at Warden Ave,29,0,3
2367069,95,YORK MILLS,WEST - 95 YORK MILLS towards YORK MILLS STATION,72906,47866837,23:59:00,23:59:00,8644,7695,Ellesmere Rd at McCowan Rd,24,1,3
2326039,95,YORK MILLS,EAST - 95B YORK MILLS towards U OF T SCARBOROUGH,72906,47866594,23:59:00,23:59:00,2471,7694,Ellesmere Rd at McCowan Rd,46,0,3

In [ ]:
# find the start and end service time for a route 
# have some thresholds of finding the min and max time 
# e.g. max before 5 AM for end time and min after 5 AM for start time?